---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# paypaltransaction

<!-- badges: start -->
<!-- badges: end -->

The goal of paypaltransaction is to retrieve one's personal paypal transactions over a specified horizon.

Lots of credit needs to go stackoverflow user *eartoolbox* and her/his code in [this thread](https://stackoverflow.com/questions/64534998/paypal-sandbox-to-live-transaction-search-api-not-working) which helped me a great deal in understanding how to access the API.

## Installation

You can install the development version of paypaltransaction like so:

``` r
# install.packages("devtools")
devtools::install_github("Lnrdbrgr/paypaltransaction")
```

## Example

Below, the basic workflow is outlined. The `user_pwd` in the function `request_access_token` is build using the 'ID:Secret' from one's personal paypal API account (`user_pwd <- paste0(ID, ":", secret)`). The transactions can only be accessed in a 30-days time window.

``` r
library(paypaltransaction)

# request the access token
token <- request_access_token(user_pwd = user_pwd, return_token_only = TRUE)

# get transactions
transaction_list <- get_transactions(access_token = acc_token,
                                     start_date = "2022-08-01",
                                     end_date = "2022-08-30")
                                     
# convert to dataframe
transaction_df <- transaction_list_to_df(transaction_list)
```

Since the transactions come in a somewhat messy list format, I added a function which converts the list to a dataframe. The resulting `transaction_df` as shown in the example code above is of schema [date, time, value, currency_code, issuer].
